resources:
- type: module
  url: /local/community/button-card/button-card.js
- type: module
  url: /local/community/mini-media-player/mini-media-player-bundle.js
- type: module
  url: /local/community/lovelace-card-mod/card-mod.js
- type: js
  url: /local/community/bar-card/bar-card.js
- type: js
  url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
- type: module
  url: /local/community/mini-graph-card/mini-graph-card-bundle.js
- type: module
  url: /local/community/weather-card/weather-card.js
- type: module
  url: /local/community/simple-weather-card/simple-weather-card-bundle.js
- type: module
  url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
- type: module
  url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
- type: module
  url: /local/community/lovelace-template-entity-row/template-entity-row.js
- type: module
  url: /local/community/custom-header/custom-header.js
- type: module
  url: /local/community/calendar-card/calendar-card.js
- type: js
  url: /local/community/lovelace-home-feed-card/lovelace-home-feed-card.js
- type: module
  url: /local/community/simple-thermostat/simple-thermostat.js
- type: module
  url: /local/community/upcoming-media-card/upcoming-media-card.js

title: Slaapkamer
views:
  - title: Slaapkamer
    cards:
