- alias: Woonkamerraam Monitor
  initial_state: 'on'
  description: Woonkamerraam Monitor
  trigger:
  - event: leave
    platform: zone
    entity_id: device_tracker.iphone_van_martijn
    zone: zone.home
  condition:
  - condition: state
    entity_id: binary_sensor.woonkamer_raam
    state: 'on'
  action:
  - data:
      message: Het woonkamerraam is nog open
      title: Raam Open!
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
    service: notify.mobile_app_iphone_van_martijn